version: '3'

services:
    mysql:
        image: mysql:5.7
        container_name: mysql.employee-erp.docker
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: database_development
            MYSQL_USER: root
            MYSQL_PASSWORD: 12345
            MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
        volumes:
            - ~/data/mysql.erpsystem.docker:/var/lib/mysql
        ports:
            - 127.0.0.1:3377:3306
        networks:
            - global

    mysql-test:
        image: mysql:5.7
        container_name: mysql-test.employee-erp.docker
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: database_test
            MYSQL_USER: root
            MYSQL_PASSWORD: 12345
            MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
        volumes:
            - ~/data/mysql-test.erpsystem.docker:/var/lib/mysql
        ports:
            - 127.0.0.1:3378:3306
        networks:
            - global

networks:
    global:
        external: true
